# Site settings
course_name: Summer Open And Reproducible Research (SOAR²) Intensive
course_description: "One liner explanation."

course_semester: "Sep 2026"

baseurl: "/soar2-test"                        # the subpath of your site, e.g. /blog/
url: "http://xiuqili-xl.github.io/"        # the base hostname & protocol for your site

schoolname: "UCSB Library"
schoolurl: "https://www.library.ucsb.edu/"

# Social media accounts (uncomment and fill in the username if you have one)
github_username: xiuqili-xl
orcid_id: 0000-0003-1796-8555
#google_scholar_id: google_scholar_id
#twitter_username: username 

program_info: |
    SOAR² is developed in partnership by Research Data Services (UCSB Library) and the Office of Undergraduate Research and Creative Activities (URCA), with support from the Open Research Community Accelerator (ORCA).


# address: |
#    UCSB Library
#    Santa Barabara, CA

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%a %-m/%-d/%Y"
onlydateformat: "%-m/%-d/%Y"
timeformat: "%-I:%M %p"

timezone: America/Los_Angeles

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
